#!/bin/bash
echo "=== Fix License Endpoint ==="
echo ""
echo "PROBLÉM:"
echo "- Starý server (PID 172776) běží jako root od 30.12.2025"
echo "- Nový kód má správně zaregistrovaný router"
echo "- Starý server endpoint nevidí (404)"
echo ""
echo "ŘEŠENÍ:"
echo "1. Musíte ukončit starý proces jako root:"
echo "   sudo kill -9 172776"
echo ""
echo "2. NEBO použít systemd service restart:"
echo "   sudo systemctl restart toozhub2"
echo ""
echo "3. NEBO najít terminál/session, kde běží a ukončit (Ctrl+C)"
echo ""
echo "4. Pak spustit nový server:"
echo "   cd /opt/toozhub2/app"
echo "   source .venv/bin/activate"
echo "   python -m uvicorn src.server.main:app --host 127.0.0.1 --port 8000"
echo ""
echo "5. Ověřit:"
echo "   curl -i http://127.0.0.1:8000/api/v1/license/status"
echo "   # Mělo by vrátit 401 (ne 404)"
